app:
  env: dev
  redis:
    server: 172.31.1.12:6380
    database: 0
    password: admin
    timeout: 2000

logging:
  config: classpath:log4j2-prod.xml

om.adc.domain: http://adc.adsgreat.com

admob:
  client_id: replace_with_your_googleapi.client_id
  client_secret: replace_with_your_googleapi.client_secret

spring:
  ## datasource
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/open_mediation?useCursorFetch=true&characterEncoding=utf8&useSSL=true&requireSSL=false
      username: root
      password: admin



