app:
  env: prod
  redis:
    server: 172.31.19.15:6379
    database: 0
    password: admin
    timeout: 2000

logging:
  config: classpath:log4j2-prod.xml

om.adc.domain: replace_with_your_om.adc.domain

admob:
  client_id: replace_with_your_googleapi.client_id
  client_secret: replace_with_your_googleapi.client_secret

spring:
  ## datasource
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://XXX:3306/open_mediation?useCursorFetch=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: XXX
      password: XXX



